
name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_login: ^6.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  go_router: ^16.2.4
  google_maps_flutter: ^2.2.8
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  # flutter_sms_plus: ^2.0.2
  url_launcher: ^6.1.7
  crypto: ^3.0.2
  shake: ^3.0.0
  # telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - lib/images/
